//File Generated By TelemetryFromXTCE.py

#ifndef GPSTELEMETRYCONTAINER_H_
#define GPSTELEMETRYCONTAINER_H_

#include "TelemetryContainer.h"

#define GPS_CONTAINER_SIZE  23

class GPSTelemetryContainer : public TelemetryContainer
{
protected:
unsigned char telemetry[GPS_CONTAINER_SIZE];

public:
    virtual int size();
    virtual unsigned char * getArray();

    char getStatus();
    void setStatus(char var);

    char getBootCounter();
    void setBootCounter(char var);

    long getResetCause();
    void setResetCause(long var);

    unsigned long getUptime();
    void setUptime(unsigned long var);

    unsigned long getTotalUptime();
    void setTotalUptime(unsigned long var);

    char getVersionNumber();
    void setVersionNumber(char var);

    short getMCUTemp();
    void setMCUTemp(short var);

    bool getINAStatus();
    void setINAStatus(bool var);

    bool getTMPStatus();
    void setTMPStatus(bool var);

    short getVoltage();
    void setVoltage(short var);

    short getCurrent();
    void setCurrent(short var);

    short getTemperature();
    void setTemperature(short var);

};

#endif /* GPSTELEMETRYCONTAINER_H_ */
