//File Generated By TelemetryFromXTCE.py

#include "GPSTelemetryContainer.h"

int GPSTelemetryContainer::size()
{
    return GPS_CONTAINER_SIZE;
}

unsigned char* GPSTelemetryContainer::getArray()
{
    return &telemetry[0];
}

char GPSTelemetryContainer::getStatus()
{
    return telemetry[0];
}
void GPSTelemetryContainer::setStatus(char uchar)
{
    telemetry[0] = uchar;
}
char GPSTelemetryContainer::getBootCounter()
{
    return telemetry[1];
}
void GPSTelemetryContainer::setBootCounter(char uchar)
{
    telemetry[1] = uchar;
}
long GPSTelemetryContainer::getResetCause()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[2] = telemetry[2];
    ((unsigned char *)&ulong)[1] = telemetry[3];
    ((unsigned char *)&ulong)[0] = telemetry[4];
    return ulong;
}
void GPSTelemetryContainer::setResetCause(long ulong)
{
    telemetry[2] = ((unsigned char *)&ulong)[2];
    telemetry[3] = ((unsigned char *)&ulong)[1];
    telemetry[4] = ((unsigned char *)&ulong)[0];
}
unsigned long GPSTelemetryContainer::getUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[5];
    ((unsigned char *)&ulong)[2] = telemetry[6];
    ((unsigned char *)&ulong)[1] = telemetry[7];
    ((unsigned char *)&ulong)[0] = telemetry[8];
    return ulong;
}
void GPSTelemetryContainer::setUptime(unsigned long ulong)
{
    telemetry[5] = ((unsigned char *)&ulong)[3];
    telemetry[6] = ((unsigned char *)&ulong)[2];
    telemetry[7] = ((unsigned char *)&ulong)[1];
    telemetry[8] = ((unsigned char *)&ulong)[0];
}
unsigned long GPSTelemetryContainer::getTotalUptime()
{
    unsigned long ulong;
    ((unsigned char *)&ulong)[3] = telemetry[9];
    ((unsigned char *)&ulong)[2] = telemetry[10];
    ((unsigned char *)&ulong)[1] = telemetry[11];
    ((unsigned char *)&ulong)[0] = telemetry[12];
    return ulong;
}
void GPSTelemetryContainer::setTotalUptime(unsigned long ulong)
{
    telemetry[9] = ((unsigned char *)&ulong)[3];
    telemetry[10] = ((unsigned char *)&ulong)[2];
    telemetry[11] = ((unsigned char *)&ulong)[1];
    telemetry[12] = ((unsigned char *)&ulong)[0];
}
char GPSTelemetryContainer::getVersionNumber()
{
    return telemetry[13];
}
void GPSTelemetryContainer::setVersionNumber(char uchar)
{
    telemetry[13] = uchar;
}
short GPSTelemetryContainer::getMCUTemp()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[14];
    ((unsigned char *)&ushort)[0] = telemetry[15];
    return ushort;
}
void GPSTelemetryContainer::setMCUTemp(short ushort)
{
    telemetry[14] = ((unsigned char *)&ushort)[1];
    telemetry[15] = ((unsigned char *)&ushort)[0];
}
bool GPSTelemetryContainer::getINAStatus()
{
    return ((telemetry[16] & 0x80) != 0);
}
void GPSTelemetryContainer::setINAStatus(bool bval)
{
    telemetry[16] &= (~0x80);
    telemetry[16] |= bval ? 0x80 : 0x00;
}
bool GPSTelemetryContainer::getTMPStatus()
{
    return ((telemetry[16] & 0x40) != 0);
}
void GPSTelemetryContainer::setTMPStatus(bool bval)
{
    telemetry[16] &= (~0x40);
    telemetry[16] |= bval ? 0x40 : 0x00;
}
short GPSTelemetryContainer::getVoltage()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[17];
    ((unsigned char *)&ushort)[0] = telemetry[18];
    return ushort;
}
void GPSTelemetryContainer::setVoltage(short ushort)
{
    telemetry[17] = ((unsigned char *)&ushort)[1];
    telemetry[18] = ((unsigned char *)&ushort)[0];
}
short GPSTelemetryContainer::getCurrent()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[19];
    ((unsigned char *)&ushort)[0] = telemetry[20];
    return ushort;
}
void GPSTelemetryContainer::setCurrent(short ushort)
{
    telemetry[19] = ((unsigned char *)&ushort)[1];
    telemetry[20] = ((unsigned char *)&ushort)[0];
}
short GPSTelemetryContainer::getTemperature()
{
    unsigned short ushort;
    ((unsigned char *)&ushort)[1] = telemetry[21];
    ((unsigned char *)&ushort)[0] = telemetry[22];
    return ushort;
}
void GPSTelemetryContainer::setTemperature(short ushort)
{
    telemetry[21] = ((unsigned char *)&ushort)[1];
    telemetry[22] = ((unsigned char *)&ushort)[0];
}
